"""added geospatial location coloumn

Revision ID: 9b1d7e3a255f
Revises: 6da16b924ec7
Create Date: 2025-08-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9b1d7e3a255f'
down_revision: Union[str, None] = '6da16b924ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('ix_restaurants_location', 'restaurants', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurants_location', table_name='restaurants', postgresql_using='gist')
    op.drop_column('restaurants', 'location')
    # ### end Alembic commands ###
